name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull abdealijaroli/jaro:latest
            docker stop jaro || true
            docker rm jaro || true
            docker run -d --name jaro -p 8008:8008 --env DB_URL="${{ secrets.DB_URL }}" abdealijaroli/jaro:latest
